---
title: "11_maps_without_crossings"
author: "anne"
date: "28 januar 2020"
output: word_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Load models and packages
```{r}
load("output/sspf/mod_sspf_allyear.rda")
load("output/mod11c_rspf_99boot_new.rda")


# mod_sspf_allyear <-  rspf_parallel(use~ step_length + I(step_length^2) + prop_young_forest + slope + crossed_rail + log_dist_building + prop_ar5_agri +  prop_ar5_bog + prop_ar5_urban + prop_old_forest + prop_water + road_cross + crossing + dist_passage + log_road_dist + road_traffic_high + log_road_dist:road_traffic_high + road_cross:road_traffic_high, data=dat, inits=ints, m=dat$strat, B=99, cl=10, method= "Nelder-Mead", link="logit")


library(ResourceSelection)
library(raster)
library(boot)

```


## Make raster stack 

#### load raster layers
```{r}

## quality map
roads_dist <- raster("maps/dist_roads.tif")
traffic_dist <- raster("maps/dist_road_traffic_high.tif")
building_dist <- raster("maps/dist_building.tif")
young <- raster("maps/prop_young_forest.tif")
old <- raster("maps/prop_old_forest.tif")

water_rs <- raster("maps/ar5_resampled/ar5_4_water.tif")
agri_rs <- raster("maps/ar5_resampled/ar5_1_agri.tif")
ruderal_rs <- raster("maps/ar5_resampled/ar5_2_ruderal.tif")
bog_rs <- raster("maps/ar5_resampled/ar5_3_bog.tif")
urban_rs <- raster("maps/ar5_resampled/ar5_5_urban.tif")
mprodcon_rs <- raster("maps/ar5_resampled/ar5_9_mprod_conifer.tif")
lprodcon_rs <- raster("maps/ar5_resampled/ar5_10_lprod_conifer.tif")
decforest_rs <- raster("maps/ar5_resampled/ar5_11_dec_forest.tif")
mixforest_rs <- raster("maps/ar5_resampled/ar5_12_mix_forest.tif")



## permeability map
log_dist_building <- raster("maps/dist_building.tif")
values(log_dist_building) <- log10(values(log_dist_building) + 1)
plot(log_dist_building)

rail_cross <- raster("maps/crossed_rail.tif")
summary(values(rail_cross))

road_cross <- raster("maps/dist_roads.tif")
values(road_cross) <- ifelse(values(road_cross)==0, 1, 0)
plot(road_cross)

dist_passage <- raster("maps/fence.tif")
values(dist_passage) <- ifelse(values(dist_passage)==0, 0, 800) #at 800 any effect of the passage seems to be gone
crossing <- raster("maps/crossings_grey.tif")
values(dist_passage) <- ifelse(values(crossing)==1, 0, values(dist_passage))
crossing <- raster("maps/crossings_high_use.tif")
values(dist_passage) <- ifelse(values(crossing)==1, 0, values(dist_passage))
crossing <- raster("maps/crossings_low_use.tif")
values(dist_passage) <- ifelse(values(crossing)==1, 0, values(dist_passage))
crossing <- raster("maps/crossings_green.tif")
values(dist_passage) <- ifelse(values(crossing)==1, 0, values(dist_passage))
plot(dist_passage)
writeRaster(dist_passage, filename="maps/test.tif", overwrite=T)

log_road_dist <- raster("maps/dist_roads.tif")
values(log_road_dist) <- log10(values(log_road_dist)+1)

dist_roads <- raster("maps/dist_roads.tif")
road_traffic_high <- raster("maps/dist_road_traffic_high.tif")
values(road_traffic_high) <- ifelse(values(dist_roads) < values(road_traffic_high),0,1)

interaction1 <- interaction2 <- road_traffic_high
values(interaction1) <- values(log_road_dist)*values(road_traffic_high)
values(interaction2) <- values(road_cross)*values(road_traffic_high)


```


#### Transform layers 
```{r}

log_dist_building <- raster("maps/dist_building.tif")
values(log_dist_building) <- log10(values(log_dist_building) + 1)
# plot(log_dist_building)


log_road_dist <- raster("maps/dist_roads.tif")
values(log_road_dist) <- log10(values(log_road_dist)+1)
# plot(log_road_dist)

dist_roads <- raster("maps/dist_roads.tif")
road_traffic_high <- raster("maps/dist_road_traffic_high.tif")
values(road_traffic_high) <- ifelse(values(dist_roads) < values(road_traffic_high),0,1)
# plot(road_traffic_high)

interaction <- road_traffic_high
values(interaction) <- values(log_road_dist)*values(road_traffic_high)
# plot(interaction)


```

#### aggregate the layers to resolution I want to use
```{r}
## Example
newLayer <- aggregate(currentLayer, fact = 4, fun = mean) # fun can be: mean, modal, min or max

## quality
log_road_dist <- aggregate(log_road_dist, fact = 4, fun = max) # max?
road_traffic_high <- aggregate(road_traffic_high, fact = 4, fun = max) # max?
log_dist_building <- aggregate(log_dist_building, fact = 4, fun = mean)

young <- aggregate(young, fact = 4, fun = mean)
old <- aggregate(old, fact = 4, fun = mean)

interaction <- aggregate(interaction, fact = 4, fun = mean)
water_rs <- aggregate(water_rs, fact = 4, fun = mean)
agri_rs <- aggregate(agri_rs, fact = 4, fun = mean)
ruderal_rs <- aggregate(ruderal_rs, fact = 4, fun = mean)
bog_rs <- aggregate(bog_rs, fact = 4, fun = mean)
urban_rs <- aggregate(urban_rs, fact = 4, fun = mean)
mprodcon_rs <- aggregate(mprodcon_rs, fact = 4, fun = mean)
lprodcon_rs <- aggregate(lprodcon_rs, fact = 4, fun = mean)
decforest_rs <- aggregate(decforest_rs, fact = 4, fun = mean)
mixforest_rs <- aggregate(mixforest_rs, fact = 4, fun = mean)


## permeability
prop_young_forest <- aggregate(prop_young_forest, fact = 4, fun = mean)
slope <- aggregate(slope, fact = 4, fun = mean)
rail_cross <- aggregate(rail_cross, fact = 4, fun = mean)
log_dist_building <- aggregate(log_dist_building, fact = 4, fun = mean)
prop_ar5_agri <- aggregate(prop_ar5_agri, fact = 4, fun = mean)
prop_ar5_bog <- aggregate(prop_ar5_bog, fact = 4, fun = mean)
prop_ar5_urban <- aggregate(prop_ar5_urban, fact = 4, fun = mean)
prop_old_forest <- aggregate(prop_old_forest, fact = 4, fun = mean)
prop_water <- aggregate(prop_water, fact = 4, fun = mean)
road_cross <- aggregate(road_cross, fact = 4, fun = mean)
crossings_grey <- aggregate(crossings_grey, fact = 4, fun = mean)
crossings_high_use <- aggregate(crossings_high_use, fact = 4, fun = mean)
crossings_low_use <- aggregate(crossings_low_use, fact = 4, fun = mean)
crossings_green <- aggregate(crossings_green, fact = 4, fun = mean)
dist_passage <- aggregate(dist_passage, fact = 4, fun = mean)
log_road_dist <- aggregate(log_road_dist, fact = 4, fun = mean)
road_traffic_high <- aggregate(road_traffic_high, fact = 4, fun = mean)
interaction1 <- aggregate(interaction1, fact = 4, fun = mean)
interaction2 <- aggregate(interaction2, fact = 4, fun = mean)



```


#### change extent (or resample???)
```{r}
str(log_road_dist)
# ncols   : int 5915
#   ..@ nrows   : int 5329
str(water_rs)
 # ..@ ncols   : int 1479
 #  ..@ nrows   : int 1333

plot(roads_dist_min)
plot(roads_dist_max)
plot(roads_dist_mean)
plot(water_rs)

plot(permeability)
e <- drawExtent()

p_crop_stationary <- crop(permeability, e)
plot(p_crop_stationary)

```


## Make brick --> ! needs to be in the same order as model variables in model !
```{r}
## quality
mybrick <- log_dist_building
mybrick <- brick(mybrick)
mybrick <- addLayer(mybrick, log_road_dist)
mybrick <- addLayer(mybrick, water_rs)
mybrick <- addLayer(mybrick, agri_rs)
mybrick <- addLayer(mybrick, ruderal_rs)
mybrick <- addLayer(mybrick, bog_rs)
mybrick <- addLayer(mybrick, urban_rs)
mybrick <- addLayer(mybrick, mprodcon_rs)
mybrick <- addLayer(mybrick, lprodcon_rs)
mybrick <- addLayer(mybrick, decforest_rs)
mybrick <- addLayer(mybrick, mixforest_rs)
mybrick <- addLayer(mybrick, road_traffic_high)
mybrick <- addLayer(mybrick, old)
mybrick <- addLayer(mybrick, young)
mybrick <- addLayer(mybrick, interaction)

# airport <- raster("maps/prop_airport.tif") # for posthoc removal

## permeability
mybrick <- raster("data/prop_young_forest.tif")
mybrick <- brick(mybrick)
mybrick <- addLayer(mybrick, raster("data/slope.tif"))
mybrick <- addLayer(mybrick, rail_cross)
mybrick <- addLayer(mybrick, log_dist_building)
mybrick <- addLayer(mybrick, raster("data/prop_ar5_agri.tif"), raster("data/prop_ar5_bog.tif"), raster("data/prop_ar5_urban.tif"))
mybrick <- addLayer(mybrick, raster("data/prop_old_forest.tif"), raster("data/prop_water.tif"))
mybrick <- addLayer(mybrick, road_cross)
mybrick <- addLayer(mybrick, raster("maps/crossings_grey.tif"), raster("maps/crossings_high_use.tif"), raster("maps/crossings_low_use.tif"), raster("maps/crossings_green.tif"))
mybrick <- addLayer(mybrick, dist_passage)
mybrick <- addLayer(mybrick, log_road_dist)
mybrick <- addLayer(mybrick, road_traffic_high)
mybrick <- addLayer(mybrick, interaction1, interaction2)

```



## Predict

#### Load model
```{r}
load("output/mod11c_rspf_99boot_new.rda")
rspf_mod <- mod11c_rspf_99boot_new
coefs <- rspf_mod$coefficients
```

#### Make newdat
```{r}
newdat <- as.data.frame(mybrick)
newdat <- data.frame(intercept=1, newdat) # makes an intercept column
str(newdat)
# newdat[,3] <- as.numeric(newdat[,3])
# table(newdat[,3])
# newdat[,3] <- ifelse(newdat[,3]==1, 0, 1)
# str(newdat)
# 
# tmp <- newdat[,15]
# sum(is.na(tmp)) #I don't get it, but it seems to correspond with the values of 800
# newdat[,15] <- as.numeric(newdat[,15])
# newdat[,15] <- ifelse(is.na(tmp), 800, 0)
# table(newdat[,15])
# str(newdat)

newdat <- as.matrix(newdat)
head(newdat)

```


#### Make and write raster
```{r}
young <- young # just use any layer, raster("maps/prop_young_forest.tif")

quality3 <- young
values(quality3) <- predprob
plot(quality3)

writeRaster(quality3, "maps/quality3.tif", overwrite = T)

# permeability <- raster("maps/permeability.tif")
# plot(permeability)

```